version: '3.8'

services:
  ubuntu:
    container_name: ubuntu
    build: .
    tty: true
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./apt-cache:/var/cache/apt/archives